name: GitHub Pages Deployment

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Branch to deploy for GitHub Pages'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
      id-token: write  
      
    steps:
      - name: Checkout the target branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.target-branch }}

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: './' 

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
