name: Switch GitHub Pages Branch

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Branch to set for GitHub Pages'
        required: true
        default: 'main'

jobs:
  switch-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the target branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.target-branch }}

      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Trigger GitHub Pages Build
        run: |
          echo "Switching to ${{ github.event.inputs.target-branch }} branch and triggering GitHub Pages rebuild."
          # Optionally touch a .nojekyll file to force a rebuild
          touch .nojekyll
          git add .nojekyll
          git commit -m "Trigger GitHub Pages rebuild"
          git push https://$MY_GITHUB_TOKEN@github.com/sramkmahr/it-startup.git HEAD:${{ github.event.inputs.target-branch }}
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
