name: Switch GitHub Pages Branch

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Branch to set for GitHub Pages'
        required: true
        default: 'main'

jobs:
  switch-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the target branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.target-branch }}

      - name: Trigger GitHub Pages Build
        run: |
          echo "Switching to ${{ github.event.inputs.target-branch }} branch and triggering GitHub Pages rebuild."
          # use a .nojekyll file to force a rebuild
          touch .nojekyll
          git add .nojekyll
          git commit -m "Trigger GitHub Pages rebuild"
          git push origin ${{ github.event.inputs.target-branch }}
