name: Switch GitHub Pages Branch

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Branch to set for GitHub Pages'
        required: true
        default: 'main'

jobs:
  switch-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Switch GitHub Pages Branch via API
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          echo "Switching GitHub Pages to ${{ github.event.inputs.target-branch }} branch"
          
          # Make the API call to switch the Pages branch
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/sramkmahr/it-startup/pages \
            -d '{"source":{"branch":"'"${{ github.event.inputs.target-branch }}"'","path":"/"}}'
          
          echo "GitHub Pages is now set to ${{ github.event.inputs.target-branch }} branch."
